# Sample .bashrc for SuSE Linux
# Copyright (c) SuSE GmbH Nuernberg

# There are 3 different types of shells in bash: the login shell, normal shell
# and interactive shell. Login shells read ~/.profile and interactive shells
# read ~/.bashrc; in our setup, /etc/profile sources ~/.bashrc - thus all
# settings made here will also take effect in a login shell.
#
# NOTE: It is recommended to make language settings in ~/.profile rather than
# here, since multilingual X sessions would not work properly if LANG is over-
# ridden in every subshell.

# Some applications read the EDITOR variable to determine your favourite text
# editor. So uncomment the line below and enter the editor of your choice :-)
#export EDITOR=/usr/bin/vim
#export EDITOR=/usr/bin/mcedit

# For some news readers it makes sense to specify the NEWSSERVER variable here
#export NEWSSERVER=your.news.server

# If you want to use a Palm device with Linux, uncomment the two lines below.
# For some (older) Palm Pilots, you might need to set a lower baud rate
# e.g. 57600 or 38400; lowest is 9600 (very slow!)
#
#export PILOTPORT=/dev/pilot
#export PILOTRATE=115200

test -s ~/.alias && . ~/.alias || true


###-tns-completion-start-###
if [ -f /home/foursixnine/.tnsrc ]; then 
    source /home/foursixnine/.tnsrc 
fi
###-tns-completion-end-###

export PATH="$HOME/perl5/bin:$HOME/.npm-global/bin:$PATH"  # ← put this line in .bashrc
eval $(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)
alias=monitor_brightness="xrandr --output HDMI-2 --brightness 0.5"

# added by travis gem
[ -f /home/foursixnine/.travis/travis.sh ] && source /home/foursixnine/.travis/travis.sh

export PATH="$HOME/.local/bin:$PATH"
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. $HOME/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh

screenfetch
