# Sample .bashrc for SuSE Linux
# Copyright (c) SuSE GmbH Nuernberg

# There are 3 different types of shells in bash: the login shell, normal shell
# and interactive shell. Login shells read ~/.profile and interactive shells
# read ~/.bashrc; in our setup, /etc/profile sources ~/.bashrc - thus all
# settings made here will also take effect in a login shell.
#
# NOTE: It is recommended to make language settings in ~/.profile rather than
# here, since multilingual X sessions would not work properly if LANG is over-
# ridden in every subshell.

# Some applications read the EDITOR variable to determine your favourite text
# editor. So uncomment the line below and enter the editor of your choice :-)
#export EDITOR=/usr/bin/vim
#export EDITOR=/usr/bin/mcedit

# For some news readers it makes sense to specify the NEWSSERVER variable here
#export NEWSSERVER=your.news.server

# If you want to use a Palm device with Linux, uncomment the two lines below.
# For some (older) Palm Pilots, you might need to set a lower baud rate
# e.g. 57600 or 38400; lowest is 9600 (very slow!)
#
#export PILOTPORT=/dev/pilot
#export PILOTRATE=115200

screenfetch &

test -s ~/.alias && . ~/.alias || true

#setup  local path
export PATH="$HOME/.local/bin:$PATH"

#setup perl paths
export PATH="$HOME/perl5/bin:$HOME/.npm-global/bin:$PATH"  # ← put this line in .bashrc
eval $(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)

#setup go paths
export GOPATH=/home/foursixnine/Projects/foursixnine.io/go:$GOPATH
export PATH="/home/foursixnine/Projects/foursixnine.io/go/bin:$PATH"  # ← put this line in .bashrc

#setup screen stuff
alias=monitor_brightness="xrandr --output HDMI-2 --brightness 0.5"

movie_mode_enable (){
    xset -dpms
    xset s off
}

movie_mode_disable (){
    xset +dpms
    xset s on
}

alias mme="movie_mode_enable"
alias mmd="movie_mode_disable"

# added by travis gem
[ -f /home/foursixnine/.travis/travis.sh ] && source /home/foursixnine/.travis/travis.sh

###-tns-completion-start-###
if [ -f /home/foursixnine/.tnsrc ]; then 
    source /home/foursixnine/.tnsrc 
fi
###-tns-completion-end-###

powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. $HOME/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh

gh-url(){
    echo $(curl -s -i https://git.io -F "url=$1" | grep Location | sed s/Location/New\ url/ )
}

if { [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; } then
        SESSION_NAME=$(tmux display-message -p '#S')
        if [ "${SESSION_NAME}" = "openqa-workspace" ]; then

                echo "We are in tmux session meant for openQA work"

                export OPENQA="$HOME/Projects/suse.com/github.com/os-autoinst"

                start_openqa() {
                        script/openqa gru -m production run & sleep 1;
                        script/openqa-scheduler & sleep 1;
                        script/openqa-websockets & sleep 1;
                        script/openqa prefork -m production --proxy -i 100 -H 400 -w 10 & sleep 1;
                }

                restart_openqa() {
                        kill $( jobs -p )
                        start_openqa
                }

                start_openqa_worker() {
                        script/worker  --instance 1 --isotovideo ${OPENQA}/os-autoinst/isotovideo --verbose
                }
        fi;
fi;

