" Generic configuration
set number
set nowrap

" Fix tab mess
set tabstop=4
set shiftwidth=4
set expandtab

" Show white spaces as a dot
set lcs+=space:·

" Powerline stuff
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
