" Generic configuration
set number
set nowrap

" Fix tab mess
set tabstop=4
set shiftwidth=4
set expandtab

" Show white spaces as a dot
set lcs+=space:·

" Fix Pasting (Which is awesome!)

function! WrapForTmux(s)
  if !exists('$TMUX')
    return a:s
  endif

  let tmux_start = "\<Esc>Ptmux;"
  let tmux_end = "\<Esc>\\"

  return tmux_start . substitute(a:s, "\<Esc>", "\<Esc>\<Esc>", 'g') . tmux_end
endfunction

let &t_SI .= WrapForTmux("\<Esc>[?2004h")
let &t_EI .= WrapForTmux("\<Esc>[?2004l")

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

" Powerline stuff
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
