" Generic configuration
set number
set nowrap

" Fix tab mess
set tabstop=4
set shiftwidth=4
set expandtab

" Show white spaces as a dot
set lcs+=space:·

" Powerline stuff

source $HOME/Library/Python/2.7/lib/python/site-packages/powerline/bindings/vim/plugin/powerline.vim
set laststatus=2
set guifont=Source\ Code\ Pro\ for\ Powerline:h15
let g:Powerline_symbols = 'fancy'
set encoding=utf-8
set t_Co=256
set fillchars+=stl:\ ,stlnc:\
set term=xterm-256color
set termencoding=utf-8

if has("gui_running")
   let s:uname = system("uname")
   if s:uname == "Darwin\n"
	set guifont=Source\ Code\ Pro\ for\ Powerline\ :h15
   endif
endif

set guifont=Source\ Code\ Pro\ for\ Powerline:h15
